
development:
  adapter: mysql2
  encoding: utf8
  database: huetiful_development
  pool: 5
  username: root
  password: rootpass
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: huetiful_test
  pool: 5
  username: root
  password: rootpass
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: huetiful_production
  pool: 5
  username: root
  password: rootpass
  socket: /var/run/mysqld/mysqld.sock
